


######################### theme kunka condigure ##############################################
# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: Übermensch
description: Community Service - Übermensch
keywords: Community Service Übermensch
url: /CommunityServiceBlog-Ubermensch
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: Home
    url: index.html
  - text: Categories
    url: navigations/categories.html
  - text: Archives
    url: navigations/archives.html
  - text: Contact
    url: navigations/contact.html
  - text: Links
    url: navigations/links.html

#Author config
author:
    name: Übermensch
    email: 15033996@imail.sunway.edu.my
    imageLink: https://res.cloudinary.com/teepublic/image/private/s--C38zCfw2--/t_Preview/b_rgb:ffffff,c_limit,f_jpg,h_630,q_90,w_630/v1463551548/production/designs/515178_1.jpg
    simpleIntro: We are team Übermensch. 
    detailIntro:
      <p>Übermensch, a concept from one of the most influencial german philosopher Friedrich Nietzsche, envision about human who are psychologically more superior than what they are now.</p>
      <p>The Übermensch is the ultimate realization of the Will to Power, but no necessarily over others. His most valuable power is over himself. "He cannot rule himself will certainty be ruled by others"- Nietzsche.</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-github-alt
    url: http://github.com/gaara4896/CommunityServiceBlog-Ubermensch

#Links
customLinks:
  - item:
    - text: Official Website
      url: http://www.kechara.com/soup-kitchen/
    - text: Facebook
      url: https://www.facebook.com/KSKPage
    message: Kechara Food Kitchen
  - item:
    - text: Übermensch
      url: https://en.wikipedia.org/wiki/%C3%9Cbermensch
    - text: Friedrich Nietzsche
      url: https://en.wikipedia.org/wiki/Friedrich_Nietzsche
    message: Reference

#comment config
disqus:
  config: false
  id: minixalpha


#################################### global configure #######################################

username: gaara4896
baseurl: /CommunityServiceBlog-Ubermensch
markdown: redcarpet
safe: false
highlighter: pygments
title: Übermensch
description: Become a better version of ourselves
theme: kunka
disqusname: minixalpha

# theme can be: hack, leap-day, merlot, midnight, minimal, modernist, slate, time-machine, kunka
# those themes are all come from GitHub Pages Themes